### ISSUE TITLE
mac os theme

### ISSUE THREAD

**Issue by ujjaldas1997** [vinceliuice/Canta-theme#10]
Hi,
        I am getting used to canta theme. I want to change my desktop theme to mac OS theme. Can you guide me? [Here](https://www.omgubuntu.co.uk/2018/03/canta-gtk-theme-rounded-corners) I have found mac OS theme which looks superb!! Currently my theme looks like 
![screenshot from 2018-03-14 09-19-30](https://user-images.githubusercontent.com/22221731/37382658-eede61c4-2769-11e8-8687-22ba122119bf.png)

Thank you.

**Comment by vinceliuice** [comment]
Sorry, Canta only support gtk3.20 or later desktops, if you want use this theme on ubuntu16.04 you can update you gtk-base version:
  sudo add-apt-repository ppa:gnome3-team/gnome3-staging
  sudo add-apt-repository ppa:gnome3-team/gnome3
  sudo apt-get update
  sudo apt-get dist-upgrade

**Comment by ujjaldas1997** [comment]
Hello @vinceliuice 
Sorry to bother you again
So far it went well for me, all the installation parts were successful. But I am still stuck on the theme part. Here is the screenshot.
![screenshot from 2018-03-15 21-52-03](https://user-images.githubusercontent.com/22221731/37476704-e29604c0-289b-11e8-8f2c-7b594d6888ea.png)
Currently I have set my theme to canta-compact.
![screenshot from 2018-03-15 21-56-49](https://user-images.githubusercontent.com/22221731/37476886-48bb19ca-289c-11e8-8e21-1cca9a0c9000.png)
Please tell me how to solve the above problem.

**Comment by vinceliuice** [comment]
![2018-03-16 00-36-43](https://user-images.githubusercontent.com/7604295/37477248-269b2be4-28b2-11e8-81de-a2102ed24bda.png)
Check those png files ,If they are missing then you should reinstall this theme and make sure no errors

**Comment by ujjaldas1997** [comment]
Hi @vinceliuice 
I reinstalled Canta from zip file, and the file path `/usr/share/themes/Canta-light-compact/gtk-3.0/assets` looks like
![screenshot from 2018-03-16 10-07-59](https://user-images.githubusercontent.com/22221731/37504162-9fb8f100-2902-11e8-94f7-b565c8087fdb.png)
I am unable to see mac-os theme. Please look into the above.
Thank you.

**Comment by vinceliuice** [comment]
That looks not works well, those borders should not have

**Comment by ujjaldas1997** [comment]
So What will I do now?

**Comment by vinceliuice** [comment]
Ubuntu18.04lts will come soon, so I recommend to upgrade to Ubuntu18.04lts when It's coming then you can use this theme, I'm using Ubuntu18.04lts daily version now, Canta works very well!

**Comment by vinceliuice** [comment]
I found a situation, when there is no "default" folder in the system theme directory: "usr/share/themes" this issue you have will happen.

**Comment by ujjaldas1997** [comment]
@vinceliuice 
Thanks for reproducing the error. By default folder, do you mean that `/usr/share/theme` should exist by default? And is there any chance that I can set mac-os theme before release of Ubuntu 18.04?

**Comment by vinceliuice** [comment]
There should be a "Default" folder in /usr/share/theme
![2018-03-18 20-48-24](https://user-images.githubusercontent.com/7604295/37565965-bdd7b0a8-2aed-11e8-8960-476544d03578.png)
[Default.zip](https://github.com/vinceliuice/Canta-theme/files/1822654/Default.zip)

**Comment by ujjaldas1997** [comment]
Hi @vinceliuice 
I don't know, if I have done it correctly :smiley: , basically I have manually copied default folder in `/usr/share/themes`. Now that `dir` contains
```
Adwaita       Bright         Canta-dark-compact   Default       KvAdapta    KvArc          KvCyan       KvGnome      KvRoughGlass      Radiance
AgingGorilla  Canta          Canta-light          Emacs         KvAmbiance  KvArcDark      KvDarkRed    KvGnomeDark  KvSimplicity      Raleigh
Ambiance      Canta-compact  Canta-light-compact  Esco          KvAmbience  KvBeige        KvDynamo     KvGray       KvSimplicityDark  Simple
Atlanta       Canta-dark     Crux                 HighContrast  Kvantum     KvCurvesLight  KvFlatLight  KvOxygen     Metabox
```
I need your review :relaxed:
