### ISSUE TITLE
GTK4 support

### ISSUE THREAD

**Issue by Thesola10** [vinceliuice/Canta-theme#101]
I really like this theme, and am wondering if there's currently an estimated timeline for reaching compatibility with the newest updates to GNOME and GTK?

For info, upstream Materia is already compatible, so maybe rebase changes on top of that?

**Comment by Thesola10** [comment]
I just tried out Canta on GNOME 40 and frankly, apart from minor issues with Blur my Shell, it's largely compatible. Now GTK4 is left!

**Comment by vinceliuice** [comment]
Support now!
