### ISSUE TITLE
Corner Radius of Logout Confirmation Buttons Broken

### ISSUE THREAD

**Issue by newk0001** [vinceliuice/Canta-theme#102]
Hello,
I love your work. I just wanted to let you know about an issue that is happening with the logout confirmation window buttons. ![issue_1](https://user-images.githubusercontent.com/64504262/126048616-fb03f0a0-7768-4079-833b-757d7f348ba8.png)
I am using:

- GNOME Version 40.2.0
- DISTRIB_ID=ManjaroLinux
- DISTRIB_RELEASE=21.1.0
- DISTRIB_CODENAME=Pahvo
- DISTRIB_DESCRIPTION="Manjaro Linux"
- Window Manager: Mutter 
- Window Manager Theme: Canta-blue-light 
- Theme: Canta-blue-light [GTK2/3] 
- Icons: Canta [GTK2/3]

**Comment by vinceliuice** [comment]
Fixed!

**Comment by newk0001** [comment]
Thank you sir!
