### ISSUE TITLE
Corner Radius of Background Image for Message Notifications Broken

### ISSUE THREAD

**Issue by newk0001** [vinceliuice/Canta-theme#103]
Hello,
I love your work. I just wanted to let you know about an issue that is happening with the corner radius of the background image for notifications.

![issue_2](https://user-images.githubusercontent.com/64504262/126048770-afc0409b-1cd0-47c2-a2ff-513726b1d6ce.png)

I am using:

GNOME Version 40.2.0
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.1.0
DISTRIB_CODENAME=Pahvo
DISTRIB_DESCRIPTION="Manjaro Linux"
Window Manager: Mutter
Window Manager Theme: Canta-blue-light
Theme: Canta-blue-light [GTK2/3]
Icons: Canta [GTK2/3]

**Comment by vinceliuice** [comment]
What's your graphics

**Comment by newk0001** [comment]
AMD® Radeon(tm) vega 8 graphics

**Comment by vinceliuice** [comment]
Fixed!

**Comment by newk0001** [comment]
Thank you sir!
