### ISSUE TITLE
Color mismatch in Gnome Files.

### ISSUE THREAD

**Issue by foliva** [vinceliuice/Canta-theme#104]
Hello!

First of all, I really like this theme. Thank you!

The issue: when GTK4 support was added I noticed that the working directory has a different colour to the rest of the path (see the different against the tabs in the about window).

![image](https://user-images.githubusercontent.com/1072568/126231497-94792ea7-68b6-499c-9829-2ebb6f53f885.png)

I'm using canta-blue-dark-compact.

This is my setup:

![image](https://user-images.githubusercontent.com/1072568/126231714-ccacff16-f207-477d-a3e7-4ff092b4146e.png)

**Comment by foliva** [comment]
More information:
If I run the installer with the option '-t blue' the theme is not blue and this happens:

![image](https://user-images.githubusercontent.com/1072568/132407650-583bece0-c6b7-4b3b-8b9e-3dddea4162f1.png)

If I just run the installer with the default option, it works fine.

Hope this helps,
Thanks!

**Comment by vinceliuice** [comment]
Are you using the last version here?

**Comment by nemoitis** [comment]
Same here. I used `./install.sh -t blue -s standard` command, but the accent color is green still. And I think `-s` didn't work either, it installed both standard and compact version even though I added standard only.

![image](https://user-images.githubusercontent.com/80112748/132451764-204bb8cc-3872-4372-b3bc-1fc8bb03e07a.png)

**Comment by foliva** [comment]
> Are you using the last version here?

Yes, I'm using the latest version from git (updated 5-Sep).

**Comment by vinceliuice** [comment]
Fixed now!
