### ISSUE TITLE
Broken On Unity

### ISSUE THREAD

**Issue by SeunLanLege** [vinceliuice/Canta-theme#11]
![screenshot from 2018-03-14 16-49-24](https://user-images.githubusercontent.com/16494314/37413600-b53a9936-27a7-11e8-8373-7cc7c2e81bba.png)

Ubuntu 16.04

**Comment by vinceliuice** [comment]
Sorry! only support ubuntu16.10 or later version desktops (gtk3.20 or later)

**Comment by SeunLanLege** [comment]
Oh OK, thanks
