### ISSUE TITLE
Gap in titlebar in gedit

### ISSUE THREAD

**Issue by coleifer** [vinceliuice/Canta-theme#12]
Lovely theme. I noticed a small qurik. In the attached screenshot you can see a gap in the window decorations where the wallpaper is visible.

![s1521056263 53](https://user-images.githubusercontent.com/119974/37426749-68ce16fc-2795-11e8-8a01-bdc1e711c663.png)

**Comment by vinceliuice** [comment]
Yes, I noticed this, Don't worry I'll fix this

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by coleifer** [comment]
Awesome!
