### ISSUE TITLE
Error with the theme

### ISSUE THREAD

**Issue by actionless** [vinceliuice/Canta-theme#13]
https://github.com/vinceliuice/Canta-theme/blob/master/HACKING.md#changing-the-color-scheme-with-script

```
bash: ./change_color.sh: No such file or directory
```

**Comment by vinceliuice** [comment]
Now I add this script file back

**Comment by actionless** [comment]
btw now materia is using a "slimer" color-changing script based on templating _colors.scss:
https://github.com/nana-4/materia-theme/blob/master/change_color.sh#L176
https://github.com/nana-4/materia-theme/blob/master/src/_sass/_colors.scss.template

**Comment by vinceliuice** [comment]
Sorry! I still don’t get the principle of modifying color for now, so I think maybe I should removed all those scripts till I understand it.

**Comment by actionless** [comment]
don't hesistate to ask anything, the script is very easy, it's just basically replacing in the template values like `%SEL_BG%` to selection bg color and so on

**Comment by vinceliuice** [comment]
Thanks, when I adjust it to work well I'll upload it.

**Comment by actionless** [comment]
thanks in advance :-)
