### ISSUE TITLE
Keyboard keys too big on GNOME 3.28

### ISSUE THREAD

**Issue by Depau** [vinceliuice/Canta-theme#14]
See screenshot below:
![screenshot from 2018-03-16 12-31-47](https://user-images.githubusercontent.com/1151321/37518611-2b522304-2916-11e8-8ac0-5a0315673e8b.png)

On-screen keyboard keys are too big on GNOME 3.28, it doesn't show the entire keyboard UI.

**Comment by vinceliuice** [comment]
FIxed now
