### ISSUE TITLE
How to remove background image in folders

### ISSUE THREAD

**Issue by roshin8** [vinceliuice/Canta-theme#15]
I would like to know how to remove the boat image in the nautilus folders
https://user-images.githubusercontent.com/3268430/37276010-89680d5a-25d8-11e8-8a02-8b307f20f696.png

**Comment by vinceliuice** [comment]
![2018-03-17 16-05-39](https://user-images.githubusercontent.com/7604295/37553219-d5349d78-29fe-11e8-929d-c38a2cd6da02.png)
Delete all background-img*.png on your theme gtk-3.0 assets folder
