### ISSUE TITLE
Spacing in menu

### ISSUE THREAD

**Issue by kash-raman** [vinceliuice/Canta-theme#16]
1. There is a spacing issue in menus like power button, right click menu. Also, the white line looks odd. 

2. If you open ubuntu software tool with dark-theme, the page is having white background with white text. 

3. Spacing issue with tabs, folder path - If you open "software and update" the tabs are not spaced properly. 

Will try to attach images.

**Comment by vinceliuice** [comment]
Can you describe it more clearly or give me some screenshot? you mean there is some issues about gnome-shell?

**Comment by kash-raman** [comment]
I like the overall theme but not able to use coz minor issue. Here are the images and issue.

1. The line-spacing is too less. Its happening in all menus. 

![1canta-spacing](https://user-images.githubusercontent.com/4085420/37562696-36232f82-2a45-11e8-9153-ca1463c07690.png)
![1default-spacing](https://user-images.githubusercontent.com/4085420/37562697-3643f550-2a45-11e8-8dc3-aadf41a2a805.png)

2. The theming is lost for ubuntu-software-center. Dark theme.
![2canta-theme](https://user-images.githubusercontent.com/4085420/37562698-36711dd2-2a45-11e8-8f70-69dbd43db905.png)
![2default_theme](https://user-images.githubusercontent.com/4085420/37562699-36a376d8-2a45-11e8-9914-ed2dc96143cd.png)

3. Tab needs spacing 
![3canta_tab](https://user-images.githubusercontent.com/4085420/37562700-36c6207a-2a45-11e8-9f80-1977d175f349.png)
![3default_tab](https://user-images.githubusercontent.com/4085420/37562701-36e65818-2a45-11e8-98e5-bcff8ca1c32c.png) 
4. When renaming, could not figureout where the cursor is. 
![4canta-rename](https://user-images.githubusercontent.com/4085420/37562702-3707f66c-2a45-11e8-9684-eeafaee5634e.png)
![4default_rename](https://user-images.githubusercontent.com/4085420/37562703-37291946-2a45-11e8-9808-10be1824f679.png)

**Comment by vinceliuice** [comment]
Are you using ubuntu16.04? then I'm sorry to tell you Canta only support Ubuntu16.10 or later (gtk3.20 or later)
