### ISSUE TITLE
Icon not centered on nautilus

### ISSUE THREAD

**Issue by FilippoFantinato** [vinceliuice/Canta-theme#19]
When I go to the root with nautilus, I see this
![screenshot from 2018-03-22 19-13-54](https://user-images.githubusercontent.com/24741245/37873359-bd3cec84-301b-11e8-9458-c40604c81de4.png)

**Comment by vinceliuice** [comment]
Thanks, I'll fix this,

**Comment by vinceliuice** [comment]
Fixed now
