### ISSUE TITLE
New GTK theme

### ISSUE THREAD

**Issue by thachngopl** [vinceliuice/Canta-theme#20]
Hi,
Sorry if I post to wrong place.
Would you please create new theme base on this design? Thank you very much

https://bassultra.deviantart.com/art/eGTK-Mockup-Kit-339505098

**Comment by vinceliuice** [comment]
I don't think it is necessary to make a theme like this because elementary os default theme is like this.

**Comment by thachngopl** [comment]
It is similar to elementaryOS default theme, but this one is flatter than that one. And the TAB control is clearer.
