### ISSUE TITLE
list supported gtk version

### ISSUE THREAD

**Issue by zllj** [vinceliuice/Canta-theme#23]
This is a recommendation. It will be good to have the gtk version supported listed on README. I am on Ubuntu 16.04, stuck with gtk 2.18 which obviously doesn't work with your theme. Really love it but too new for my old OS.
Thank you!

**Comment by vinceliuice** [comment]
Sorry this theme only support GTK+ 3.20 or later

**Comment by qwertychouskie** [comment]
This is already listed in the README, under "Info".

**Comment by fenlan** [comment]
This is a great beautiful theme. Although it doesn't work very well for my Ubuntu 16.04, I really want to install this theme for the next 18.04
