### ISSUE TITLE
occupy too much memory

### ISSUE THREAD

**Issue by fenlan** [vinceliuice/Canta-theme#24]
it occupy memory about 25% in my 1G mechine

**Comment by vinceliuice** [comment]
This is not a bug, because this theme is based on Materia theme so it uses a lot of animation effects, if you don't need it you can use gnome-tweak-tool to close all animation effects, and by the way, 1G memory is too small for linux desktops like gnome-shell

**Comment by fenlan** [comment]
o, thanks! I just test it in my old computer. It is really beautiful!!!
