### ISSUE TITLE
There are no icons for some settings items

### ISSUE THREAD

**Issue by marcosvbras** [vinceliuice/Canta-theme#25]
Items without icon: Wifi, Background, Region & Language, Universal Access.

![screenshot from 2018-04-29 10-45-44](https://user-images.githubusercontent.com/8402880/39407324-a20a23f6-4b9a-11e8-88f5-93e3fda93801.png)

**Comment by vinceliuice** [comment]
Canta icon theme use numix-icon-theme-circle icon theme for Inherits,

so if you want a better experience you should install numix-circle first

numix-icon-theme-circle : https://github.com/numixproject/numix-icon-theme-circle
