### ISSUE TITLE
XFWM4 window decorations support

### ISSUE THREAD

**Issue by xieve** [vinceliuice/Canta-theme#27]
Overall I'm really pleased with this theme, but one thing really annoys me: As Xfce mostly uses its own Xfwm instead of gtk (please correct me if I'm wrong but e.g. Nautilus works just fine) I have got to use another theme's window decorations, which is a bit ugly if you ask me. Soo it'd be great if you could add support to that or maybe even just tell me where the window-decoration-specific "code" or whatever is and I try to do it myself. Currently I'm too stupid to find this just by looking at the source with barely a clue of how it works.

**Comment by qwertychouskie** [comment]
Actually this seems to be a bug in `install.sh` when running it with `sudo`, running it without `sudo` then manually copying the files from `~/.themes/` to `/usr/share/themes` works on my system.

**Comment by xieve** [comment]
Maybe you could add the fact that it does support Xfce window decoration in your readme. I just looked into this again and it seems like this is something that happened because I just tried to install it via the AUR pacman package which seems to run `install.sh` as root. I'm gonna look into the PKGBUILD and try to solve it there. Thanks for taking the time!

**Comment by xieve** [comment]
I just realized that that package was even marked outdated, so I guess I'll try to fix more than just this I guess.

**Comment by xieve** [comment]
Looking at the themes folder though, the xfwm4 folder is present in there, so I tried to compile a list with files which were copied to ~/.themes but not to /usr/share/themes.

    $ cd .themes
    ~/.themes $ find Canta | sort > /tmp/1.txt          
    ~/.themes $ cd /usr/share/themes/                      
     /usr/share/themes $ sudo find Canta | sort > /tmp/2.txt
     /usr/share/themes $ comm -23 /tmp/1.txt /tmp/2.txt

Output: None. This is confusing, if you ask me. I'll now try to restart xfce, which means I gotta send this.

**Comment by xieve** [comment]
Restarting seemingly does the trick. I'm now gonna start converting your install.sh into a PKGBUILD.
