### ISSUE TITLE
Merge recent upstream commits if possible

### ISSUE THREAD

**Issue by qwertychouskie** [vinceliuice/Canta-theme#29]
e.g. https://github.com/nana-4/materia-theme/commit/4e2aa1c3dc2a91de44c37d439a33a39e29fa1c4a

Unfortunately this repo doesn't have the commit history for Materia, but one could make a diff between what is currently in this repo and Materia at the commit it was forked at, then apply that diff on top of the current Materia code, then commit THAT diff to this repo...

**Comment by vinceliuice** [comment]
Thanks I'll fix this
