### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by RONNY7669** [vinceliuice/Canta-theme#30]
Hello! I really loved the theme, especially the square versions, my only complaint, however, is with the little art of wallpaper that appears in the upper corner in the file manager.
In a next update, could a version come without the art of wallpaper?

**Comment by vinceliuice** [comment]
Actually, this can be easy solved, you can just delete all background-img png files on gtk-3.0/assets/ then you will see aversion without wallpaper, and I think I can provide a install script for no art wallpaper version

**Comment by RONNY7669** [comment]
Thanks! very easy!
