### ISSUE TITLE
Unreadable menus with dark shell theme

### ISSUE THREAD

**Issue by goyodiaz** [vinceliuice/Canta-theme#33]
Unselected items in app menus and window menus are unreadable with canta-dark shell theme and the other dark sell themes too.

![appmenu](https://user-images.githubusercontent.com/1676326/41732328-076376a2-7581-11e8-9a18-5498cef254da.png)

**Comment by vinceliuice** [comment]
Did you changed system default gdm or gnome-shell theme，All Canta dark themes works well on my desktop

**Comment by goyodiaz** [comment]
Oh, yes. I was using the pop GDM session from POP!_OS. Switching to the gnome session fixed it. Sorry for the noise, this has bitten me before because I never expect the session affecting how shell themes look (but obviously it does).
