### ISSUE TITLE
xfce4 appmenu and plank issues

### ISSUE THREAD

**Issue by numberokta** [vinceliuice/Canta-theme#34]
Awesome theme...
But when i use this theme, "appmenu" use a lot of cpu (about 20-30%) and when i right click on icons in "plank", background color stuck on hovering.
everything else works great.

- GTK+ v3.22.30-2
- Ubuntu v18.04
- Xfce v4.12 + metacity v1:3.28.0-1
- xfce4-appmenu-plugin v0.6.94 (Source: vala-panel-appmenu)

![untitled](https://user-images.githubusercontent.com/20727200/43242843-890d787c-90b8-11e8-93e2-f39dba394741.png)
![untitled1](https://user-images.githubusercontent.com/20727200/43242844-8940256a-90b8-11e8-98af-ed128c48f161.png)

**Comment by vinceliuice** [comment]
Someone has feedback this question before, it seems to be caused by the animation effect, I am trying to solve this problem.
