### ISSUE TITLE
Files background image NOT showing

### ISSUE THREAD

**Issue by 13addata** [vinceliuice/Canta-theme#36]
![screenshot from 2018-09-23 18-08-40](https://user-images.githubusercontent.com/26506056/45933502-5d6b2700-bf5c-11e8-9bc8-7baa97bd7962.png)

I really like this design however it doesn't show. 
I am using nautilus. 

![screenshot from 2018-09-23 18-35-46](https://user-images.githubusercontent.com/26506056/45933683-87721880-bf5f-11e8-955f-e55ab4edf729.png)

**Comment by vinceliuice** [comment]
Sorry, I foget add this to readme, if you want to install the version with background img of nautilus yiu should run ./Install_with_background_img

**Comment by 13addata** [comment]
Solved.  Thank You!
