### ISSUE TITLE
Install script should be ask to install icons

### ISSUE THREAD

**Issue by simonbcn** [vinceliuice/Canta-theme#37]
To install the Canta icons I have to change the folder to `.../src/icons` and execute `install.sh`.
Wouldn't it be more comfortable (_and logical_) if the installation script of the theme asked if we want to install and activate the icons of this theme?

**Comment by vinceliuice** [comment]
You are right! I'll add this to installation script

**Comment by simonbcn** [comment]
Or better if you add one option (like `--gdm`) to choose install the icons too.

**Comment by vinceliuice** [comment]
Good idea! I add this to install.sh now!
