### ISSUE TITLE
Install_with_background_img should pass the options to install.sh

### ISSUE THREAD

**Issue by simonbcn** [vinceliuice/Canta-theme#39]
`install.sh` has several options to change the installation path, etc... but `Install_with_background_img`doesn't pass any option when it calls to `install.sh`:
```
...
# install
echo "Start Install..."
./install.sh
echo 
echo "Install finished!"
...
```

I think it would be simpler, if you want to keep the option to install the background image of Nautilus, to create an extra option in the main script (`install.sh`) for that and delete this secondary script.

**Comment by vinceliuice** [comment]
You are right! I can create an extra option in the main script

**Comment by simonbcn** [comment]
ok, but there is errors in script:

1. `install.sh --help` says: `-b, --bgimg VARIANT      Specify theme nautilus background image variant(s)` but there isn't variant for this option.
2. And after install the image, it calls itself!? and without parameters? 
3. If I specify the `--icon` option it installs only the icon set but not the theme. With `--gdm` option installs gdm theme and gnome theme.

My suggestion: https://hastebin.com/temonelosu
