### ISSUE TITLE
Appearance Issues on Ubuntu 14.04

### ISSUE THREAD

**Issue by mhubrich** [vinceliuice/Canta-theme#4]
First of all, good job creating this theme. I really like how the screenshots look like.

However, I can't manage to make the theme work on my environment:
- Ubuntu 14.04
- Unity 7.2.6
- GTK 3.10.8
- GTK 2.24.23
- I did successfully run `sudo apt-get install gtk2-engines-murrine gtk2-engines-pixbuf`

I cloned your repository and ran `./install.sh`. I didn't get any errors during installation. Here is what the theme looks like for me:
![Screenshot of Canta Theme](https://user-images.githubusercontent.com/20369248/37244898-c41430ea-2444-11e8-8b41-7bdc0cc8c238.png)

Everything is a little bit off and odd. Any ideas?

**Comment by vinceliuice** [comment]
Sorry my friend, this theme just support gtk3.20 or later version desktops (means only support ubuntu 16.10 or later) for now

**Comment by fayjie92** [comment]
Can we get gtk 3.18 support? As ubuntu 16.04 is still the LTS version.

**Comment by mhubrich** [comment]
> Sorry my friend, this theme just support gtk3.20 or later version desktops (means only support ubuntu 16.10 or later) for now

Alright, thanks for the answer anyway. I understood the requirement information in the README.md as in "GTK 2 **or** GTK 3.20". But it's actually an "and". Thanks for clearing this up.
