### ISSUE TITLE
install.sh has a bug with multi options

### ISSUE THREAD

**Issue by Sherlock-Holo** [vinceliuice/Canta-theme#40]
when I try `./install.sh -d "${pkgdir}/usr/share/themes"` , everything is ok.
but if i add `-b` such as `./install.sh -b -d "${pkgdir}/usr/share/themes"` or `./install.sh -d "${pkgdir}/usr/share/themes" -b`, the ` -d "${pkgdir}/usr/share/themes"` is invalid, because `makepkg` reports something like 

> rm: 无法删除'/usr/share/themes/Canta/metacity-1/build/Canta-square/metacity-1/build/Canta-compact/metacity-1/shade_unfocused_pressed.png': 权限不够

I think there are some problems in install.sh

**Comment by vinceliuice** [comment]
I update it now you can try again

**Comment by Sherlock-Holo** [comment]
thx
