### ISSUE TITLE
the natilus title has some bugs

### ISSUE THREAD

**Issue by Sherlock-Holo** [vinceliuice/Canta-theme#41]
![image](https://user-images.githubusercontent.com/10096425/46452014-1555cb00-c7cc-11e8-9728-31a960facd88.png)

there is a bug or maybe my [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=canta-theme-git) has some problems

**Comment by Sherlock-Holo** [comment]
Thanks for your theme, I am waiting for your repair

**Comment by Sangeppato** [comment]
Same issue on 3.30...
BTW thanks for your effort, the theme is amazing!

**Comment by 13addata** [comment]
I actually read this issue yet the system auto-updated to nautilus 3.30...  Feel so bad....
Nice theme CAN NOT AGREE MORE.   Waiting for the fix.  Thank you! :rocket:

**Comment by Sangeppato** [comment]
@vinceliuice 
The "Materia" theme had the same issue and today nana-4 released a fix which solves it: https://github.com/nana-4/materia-theme/commit/ea65ff3f36bca605581beadd430afc8cb9dde3b5

It should work here as well, right?

**Comment by vinceliuice** [comment]
Well thanks @Sangeppato , that helps a lot !

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by Sherlock-Holo** [comment]
[PKGBUILD](https://fars.ee/oWNs/)
I install on my computer but it still has this bug, is it the PKGBUILD problem?
![image](https://user-images.githubusercontent.com/10096425/46844949-c7fcdd80-ce0b-11e8-8217-7709475fed62.png)

**Comment by vinceliuice** [comment]
Sorry! I foget to draft new release file, I've drafted a new release file now : https://github.com/vinceliuice/Canta-theme/releases/tag/2018-10-12 ,   you can update this PKGBUILD,  maybe that's the reason.

**Comment by Sangeppato** [comment]
@vinceliuice
No problem! Thanks again for your awesome theme, I really think it's the best around!
