### ISSUE TITLE
Path, check box, background displaying bugs

### ISSUE THREAD

**Issue by 13addata** [vinceliuice/Canta-theme#42]
![screenshot from 2018-10-06 12-54-09](https://user-images.githubusercontent.com/26506056/46575712-8215c480-c988-11e8-92ac-89ff69574807.png)

The background image is not showing. It was installed by the 10.01 release with the ./install.sh -b command.   Nautilus ver 3.28.1-1.1

Also, 
the check box is like a red square box and it looks the same either checked or unchecked.

the highlighted path should be like a capsule shape?

**Comment by vinceliuice** [comment]
All png files are missing, please reinstall again

**Comment by 13addata** [comment]
> All png files are missing, please reinstall again

I already tried. 
Including removing all the files and even reinstall the whole system cuz I thought it was cause by my mistake... lol

Installing early commits didn't help neither.

**Comment by vinceliuice** [comment]
I'll check the install script and try on my computer, maybe the script have some issues

**Comment by 13addata** [comment]
![screenshot from 2018-10-06 17-48-20](https://user-images.githubusercontent.com/26506056/46576073-09b30180-c990-11e8-9a4f-ca5b2e83ba4c.png)

based on what you said, I just check out the assets folder and I found all of these files has a red cross. 
Is it because I was running the script under root user and there are auth problems?

**Comment by vinceliuice** [comment]
That must be the reason why assets resources can not be used, you can delete all canta* and try again

**Comment by 13addata** [comment]
by doing delete all canta theme files and reinstall gives the same result. I just change the permissions of all the files to 777 and then it works properly.

**Comment by qwertychouskie** [comment]
The `install.sh` script probably needs a `chmod 755`.
