### ISSUE TITLE
Change Canta base color

### ISSUE THREAD

**Issue by stefanocirici** [vinceliuice/Canta-theme#43]
Can you provide me some info in how to change the default theme color? I would like to make the dark variant darker.

**Comment by vinceliuice** [comment]
You can edit this two color files:
![2018-10-08 19-09-58](https://user-images.githubusercontent.com/7604295/46605989-e02fdc80-cb2d-11e8-9f0b-28952de1d1d4.png)

**Comment by stefanocirici** [comment]
Wow very fast response! Thank you very much

**Comment by vinceliuice** [comment]
You can change $titlebar_bg_color \ $bg_color \ $base_color ... to make Background colors more darker

**Comment by stefanocirici** [comment]
How to compile then?
I am using:
> ./install.sh -c dark -s compact -r standard

but I am not sure is doing anything, even after restarting gnome (ALT+F2, r)

**Comment by vinceliuice** [comment]
Install sassc for compile, then run ./parse-sass.sh

**Comment by stefanocirici** [comment]
It's all that I needed. Thank you.

**Comment by stefanocirici** [comment]
Just as note here is my diff:

`44,45c44,45
< $bg_color:         if($variant == 'light', $grey_100, fade($green_grey_900));
< $base_color:       if($variant == 'light', darken($white, 1%),    fade($green_grey_800));
---
> $bg_color:         if($variant == 'light', $grey_100, fade($green_grey_700));
> $base_color:       if($variant == 'light', darken($white, 1%),    fade($green_grey_600));
47,48c47,48
< $lighter_bg_color: if($variant == 'light', $grey_50,  fade($green_grey_700));
< $alt_lighter_bg_color: if($variant == 'light', $grey_200, fade($green_grey_700)); // for gnome-shell sub menu
---
> $lighter_bg_color: if($variant == 'light', $grey_50,  fade($green_grey_500));
> $alt_lighter_bg_color: if($variant == 'light', $grey_200, fade($green_grey_600)); // for gnome-shell sub menu
53,54c53,54
< $titlebar_bg_color:     if($titlebar == 'dark', if($variant == 'light', $green_grey_700, $green_grey_900), $white);
< $alt_titlebar_bg_color: if($titlebar == 'dark', $green_grey_700, $grey_300);
---
> $titlebar_bg_color:     if($titlebar == 'dark', if($variant == 'light', $green_grey_700, $green_grey_800), $white);
> $alt_titlebar_bg_color: if($titlebar == 'dark', $green_grey_600, $grey_300);
`

I will play with colors a little bit but this theme is already awesome.
