### ISSUE TITLE
the f1ab9d5 commit break -b option

### ISSUE THREAD

**Issue by Sherlock-Holo** [vinceliuice/Canta-theme#44]
update to f1ab9d5 commit, when isntall with `-b` option, it report:

> Installing specify theme with nautilus background image ...
> 
> == Generating the CSS...
> sassc: error while loading shared libraries: libsass.so.0: cannot open shared object file: No such file or directory
> 
> Done.

without `-b` option it install normally

**Comment by vinceliuice** [comment]
You can reinstall sassc and try again, there must be something when running sassc to generate CSS files

**Comment by Sherlock-Holo** [comment]
oh my arch is not the latest so it builds failed, i update and re-build successful
