### ISSUE TITLE
GTK3 file save menus shrunk

### ISSUE THREAD

**Issue by acerspyro** [vinceliuice/Canta-theme#50]
Canta:
![image](https://user-images.githubusercontent.com/4400999/48290309-65195900-e440-11e8-9b19-5461c102393b.png)

Adwaita:
![image](https://user-images.githubusercontent.com/4400999/48290336-7bbfb000-e440-11e8-9704-347e5064da46.png)

I am not sure if this is a bug that can go away with an update or if this is a bug in Gnome/GTK as this issue is reproducible on every theme except Adwaita.

The application displayed here is Atom 1.32.1

**Comment by vinceliuice** [comment]
This theme only support gnome 3.20 or later

**Comment by acerspyro** [comment]
I am running Gnome 3.30.2
