### ISSUE TITLE
The button background is incomplete when the mouse is hovered

### ISSUE THREAD

**Issue by Hentioe** [vinceliuice/Canta-theme#57]
This is `Adapta` theme:
![image](https://user-images.githubusercontent.com/13946976/50673579-c95c3180-1019-11e9-9084-2ea9d43db6de.png)

This is `Canta`:
![image](https://user-images.githubusercontent.com/13946976/50673599-f0b2fe80-1019-11e9-8708-686ce6db5f99.png)

Software: [EasySSH](https://github.com/muriloventuroso/easyssh)

Steup:

1. Create an ssh connection using the EasySSH
1. Place the mouse over the close button of the connection tab

Canta Version: Latest commit of the current main branch

**Comment by vinceliuice** [comment]
现在ok了

**Comment by Hentioe** [comment]
已确认修复，真迅速，感谢！

**Comment by vinceliuice** [comment]
哈哈,不客气
