### ISSUE TITLE
Matching theme for Mastodon

### ISSUE THREAD

**Issue by Stanzer** [vinceliuice/Canta-theme#58]
Hi there,
This is not an issue at all, I just wanted to let you know that I love this theme so much that I decided to create a matching Stylus theme (Dark) for the Mastodon web client. https://userstyles.org/styles/167537/canta-dark-for-mastodon

Keep up the good work. (And feel free to delete this post once you read it!)

Cheers.

**Comment by vinceliuice** [comment]
Thank you for your love of my work. the stylish theme looks great！
