### ISSUE TITLE
音量调节的进度条不够分明

### ISSUE THREAD

**Issue by Hentioe** [vinceliuice/Canta-theme#60]
这是 Adapta 主题的：

![image](https://user-images.githubusercontent.com/13946976/51492954-89a19200-1dee-11e9-8dcc-f92c2cdb9151.png)

这是 Canta 的：

![image](https://user-images.githubusercontent.com/13946976/51492978-9e7e2580-1dee-11e9-9938-e657b13303c2.png)

为什么绿色线条上又用绿色线条呢？是不是不太合理啊。

**Comment by vinceliuice** [comment]
新版的shell3.30更新后定义levelbar的css类名更新了，没事，我会修复这个的

**Comment by vinceliuice** [comment]
一直用的台式机所以没注意到这个问题

**Comment by Hentioe** [comment]
@vinceliuice 台式机也有这个界面，把鼠标放在音量图标上然后直接滚动滑轮（不要左键单击）就出来了。

**Comment by vinceliuice** [comment]
还有这操作?我回去试试, 对啦,已经修复了,你可以下载最新的试试

**Comment by Hentioe** [comment]
完美解决！
