### ISSUE TITLE
不兼容 GParted？

### ISSUE THREAD

**Issue by Hentioe** [vinceliuice/Canta-theme#61]
起初我一直以为是 GParted 自己的问题，但是我发现我换上别的主题就正常了。这是不是主题的问题？

Canta:
![image](https://user-images.githubusercontent.com/13946976/51872020-0bfff800-2393-11e9-9dca-ed06a1fceabd.png)

Arc:
![image](https://user-images.githubusercontent.com/13946976/51872027-11f5d900-2393-11e9-87fe-5d2134a61652.png)

**Comment by qwertychouskie** [comment]
Maybe canta is installed user-local rather than system-wide?  Because GParted is run as root.

**Comment by Hentioe** [comment]
@qwertychouskie Yes, you reminded me, I forgot this. Next I will verify it. Thanks.

**Comment by vinceliuice** [comment]
这是root应用，你可以将目前用户的.themes文件夹链接到root目录下，也可以root权限运行主题的安装脚步安装到usr/share/themes目录
