### ISSUE TITLE
汉化

### ISSUE THREAD

**Issue by jerry123li** [vinceliuice/Canta-theme#63]
部分未能正常汉化
![qq 20190219192759](https://user-images.githubusercontent.com/42824360/53012005-c8be1400-347c-11e9-8c19-0651ad7d3bdb.png)
![qq 20190219192747](https://user-images.githubusercontent.com/42824360/53012019-d378a900-347c-11e9-8475-4f87ec5517bd.png)

**Comment by vinceliuice** [comment]
汉化和主题无关的，这个需要系统组件支持

**Comment by jerry123li** [comment]
那请问如何配置呢？小白，不是太懂。问题描述的也不正确，请理解。

**Comment by vinceliuice** [comment]
你用的应该是desktop-icon的gnome-shell插件吧，这个需要和插件的作者反馈请求提供汉化支持

**Comment by vinceliuice** [comment]
现在这个插件没有汉化版本的话那就没有办法,只能等他支持中文
