### ISSUE TITLE
Notifications have transparent background in Cinnamon

### ISSUE THREAD

**Issue by Janne-d-Arc** [vinceliuice/Canta-theme#64]
Notifications have transparent background in Cinnamon making text difficult to read:
![Canta](https://user-images.githubusercontent.com/13596575/54891427-f4189200-4e72-11e9-8e2b-87b159e31b97.png)

Can you fix this, please?

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Can you tell me what's you system version and cinnamon version? and can you help me how to make a test notification

**Comment by Janne-d-Arc** [comment]
Sure, I would love to help improve your awesome themes!

I'm using Linux Mint 19.1 64-bit with Cinnamon 4.0.9. To test the notifications you can go to "System Settings", and then to "Notifications", there is a button to test the notifications. Also you can open a Terminal and type the command: `notify-send "text to show in notification"`

Thank you for supporting Cinnamon.

**Comment by vinceliuice** [comment]
All fixed now! have a nice day!

**Comment by Janne-d-Arc** [comment]
> All fixed now! have a nice day!
Thank you so much! This problem has been fixed ...but I have found a similar issue. The text in the notification history (the notification applet in the system tray) appears like this:
![Canta](https://user-images.githubusercontent.com/13596575/54981053-0119ac00-4f6d-11e9-8916-bc603ffe6052.png)
This only affects the light variants of the theme, with the dark versions the text is displayed correctly.

**Comment by vinceliuice** [comment]
I foget notifications on menu, I'll fix soon

**Comment by Janne-d-Arc** [comment]
Thank you very much! 

I hope I'm not too annoying but I also found another small problem, the "Loading" message that appears in the corner of the file manager (Nemo in my case) when it is loading files and thumbnails has no background, making the text difficult to read.

Canta, Matcha and Vimix are affected by this.

**Comment by vinceliuice** [comment]
Ok I'll check this and find a way to fix it

**Comment by Janne-d-Arc** [comment]
Sorry for the late reply, this is a picture showing what I'm talking about:
![bitmap](https://user-images.githubusercontent.com/13596575/56873717-149bb500-69fa-11e9-9ae6-ad30c3d9bbdb.png)
Canta, Matcha and Vimix are affected by this. Qogir works fine.

**Comment by vinceliuice** [comment]
No problem! I'll fix this

**Comment by vinceliuice** [comment]
Fixed now

**Comment by Janne-d-Arc** [comment]
> Fixed now

Thank you! Now your themes look even better.

Sierra, Mojave, Vimix, Canta and Qogir work perfectly now ...only Matcha still has this problem.

**Comment by vinceliuice** [comment]
OK, I'll fix matcha later

**Comment by vinceliuice** [comment]
And by the way, Square variant had been removed from canta since updated to gnome 3.32 version

**Comment by Janne-d-Arc** [comment]
> And by the way, Square variant had been removed from canta since updated to gnome 3.32 version

I see, I just updated the theme without realizing that the Square version was no longer included, I'm sorry.
