### ISSUE TITLE
Changing theme to custom colour not working.

### ISSUE THREAD

**Issue by vaskark** [vinceliuice/Canta-theme#68]
Hi. I've followed the instructions in the HACKING.md file and changed the colour to my specified one. I'm assuming it recreates the default theme colour and leaves blue and indigo alone.
First, it doesn't seem I have all the files listed in step 1, or they are in different locations. But I tried to find them all.
Then I ran ./render-assets.sh and it seemed to work.
However, the new colour did not appear once installed.
Can anyone offer some advice? I'm on Ubuntu 19.04.

Thanks.

**Comment by ceyhunnabiyev** [comment]
Same problem for me.

**Comment by vinceliuice** [comment]
Use gedit to change this, search #FFAC00 and replace it then save

**Comment by vaskark** [comment]
I did that. Nothing really changed. I think more edits are needed elsewhere in the css files. Anyhoo, not a big deal. Great theme, btw.

**Comment by ceyhunnabiyev** [comment]
@vaskark, for me worked. Can you run `./install.sh` ?
Thanks, @vinceliuice
