### ISSUE TITLE
Activities button is black in GNOME Shell

### ISSUE THREAD

**Issue by gregorydk** [vinceliuice/Canta-theme#70]
The 3 dots that is the Activities button are black in Canta (all variants except dark and light) and thus invisible on the black top bar in GNOME Shell.

Same bug as https://github.com/vinceliuice/Canta-theme/issues/8

**Comment by gregorydk** [comment]
@vinceliuice You can solve this bug by copying activities.svg and activities-active.svg from Canta-dark to Canta (for all colours).

**Comment by vinceliuice** [comment]
Fixed
