### ISSUE TITLE
Gnome Shell popup menus are aligned incorrectly

### ISSUE THREAD

**Issue by dslul** [vinceliuice/Canta-theme#72]
When using the gnome shell theme, popup menus are not always aligned correctly under the icon. Here is the same issue in the arc theme repo https://github.com/NicoHood/arc-theme/issues/108

Here are a couple of images:
![image](https://user-images.githubusercontent.com/6121202/60453199-ca6cc500-9c30-11e9-9524-5029534794a8.png)
![image](https://user-images.githubusercontent.com/6121202/60453212-d5275a00-9c30-11e9-950a-478acedcdb44.png)

Here is how it should be, with the menus right under the icon (using the adapta theme):
![image](https://user-images.githubusercontent.com/6121202/60453273-06a02580-9c31-11e9-889f-d590bf235963.png)
![image](https://user-images.githubusercontent.com/6121202/60453283-0c960680-9c31-11e9-8fa0-9ae0dcf8cd2e.png)

**Comment by dslul** [comment]
Changing these values seems to have fixed the issue:
.popup-menu-boxpointer {
  -arrow-border-radius: 1px;
  ....
  -arrow-base: 48px;
.candidate-popup-boxpointer {
  ...
  -arrow-base: 48px;

![image](https://user-images.githubusercontent.com/6121202/60455419-985e6180-9c36-11e9-9e71-2db9cb7fe4fd.png)

**Comment by vinceliuice** [comment]
Thanks I'll fix this

**Comment by vinceliuice** [comment]
Fixed
