### ISSUE TITLE
Text is too pale in menus in Gnome Shell 3.34.0

### ISSUE THREAD

**Issue by rodolpheh** [vinceliuice/Canta-theme#75]
I noticed that since the Gnome 3.34 update, the text are too pale in menus, making them unreadable. See a picture attached as an example :

![image](https://user-images.githubusercontent.com/4491499/65393585-e04adb80-dd82-11e9-8589-a1f2fd739100.png)

Switching between the dark and light theme doesn't change anything.

**Comment by vinceliuice** [comment]
Can you tell me you system version?

**Comment by rodolpheh** [comment]
```
~ 
➜ uname -o -m -r   
5.3.1-arch1-1-ARCH x86_64 GNU/Linux

~ 
➜ gnome-shell --version
GNOME Shell 3.34.0
```
Are these the informations you needed ?

**Comment by vinceliuice** [comment]
OK, I'll fix this

**Comment by rodolpheh** [comment]
One of the noticeable thing that seems to have changed between Gnome 3.32 and Gnome 3.34 regarding the menus is the `color` that is now set to `$fg_color` in [`_common.scss`](https://gitlab.gnome.org/GNOME/gnome-shell/blob/master/data/theme/gnome-shell-sass/_common.scss#L543). Could it be the culprit ?

**Comment by rodolpheh** [comment]
It is fixed by the way. Thank you for your wonderful work, I'll close the issue. :tada:
