### ISSUE TITLE
Budgie desktop menu broken

### ISSUE THREAD

**Issue by gsbhasin123** [vinceliuice/Canta-theme#79]
On all variants.
![image](https://user-images.githubusercontent.com/48339289/70381993-31da1f80-1909-11ea-8636-6f50060bcbd6.png)
The blue thing shouldn't be there.  It's on all versions, light and dark :(

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by gsbhasin123** [comment]
See my description above.

**Comment by gsbhasin123** [comment]
On a side note:
Also, can your themes have plugins in the Oomox software? https://github.com/themix-project/oomox
i made my own theme, https://gitlab.com/Gsbhasin84/materiav2, and would love to make spins on it using Qogir, Vimix, and Canta bases. thx

**Comment by gsbhasin123** [comment]
Thanks @vinceliuice hope its solved

**Comment by gsbhasin123** [comment]
Ok i rebooted, its fixed now i dunno how

**Comment by gsbhasin123** [comment]
Just need to get an oomox plugin now
