### ISSUE TITLE
Icon for Activities button in gnome shell

### ISSUE THREAD

**Issue by ricwtk** [vinceliuice/Canta-theme#8]
Hi, this is a great theme, thanks for your work. Just noticed that the activities button on the gnome shell top panel in Canta/Canta-compact is black, which is invisible due to the black background. It probably should be white, like in Canta-dark/Canta-dark-compact.

**Comment by vinceliuice** [comment]
Thanks! did not notice this before, I'll fix this

**Comment by vinceliuice** [comment]
Fixed
