### ISSUE TITLE
New TitleBar layout in Geary 3.35.2

### ISSUE THREAD

**Issue by likeadoc** [vinceliuice/Canta-theme#81]
Unfortunately the team behind Geary changed the layout of the titlebar recently. The separator element in the title bar is no longer part of geary-titlebar-left. It now belongs to the parent box element. As a result the separator element in the title bar is not displayed.

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by likeadoc** [comment]
Thanks;)

**Comment by vinceliuice** [comment]
Fixed!
