### ISSUE TITLE
inconsistant title bar corner

### ISSUE THREAD

**Issue by QuakeString** [vinceliuice/Canta-theme#83]
first of all I'm a fan of this theme, and the only reason I use gnome instead of kde.
here is my problem.
some apps bottom corner are round and some apps bottom corner is not round, sharp. how to fix it ?
![text4670-8](https://user-images.githubusercontent.com/5375918/75646284-84f90f80-5c77-11ea-8080-96297fd1b39e.png)

**Comment by vinceliuice** [comment]
Tell me the names of these softwares, I‘ll try to set rounded corners, but all non-csd windows can not be set rounded corner

**Comment by QuakeString** [comment]
These are the apps I use very frequently every day.
1. gnome-terminal
2. firefox
3. Telegram Desktop
4. Mailspring
5. Libreoffice

**Comment by vinceliuice** [comment]
Unfortunately none of these software can set rounded corners

**Comment by QuakeString** [comment]
oh ! not even gnome-terminal ?
that really strange.

**Comment by QuakeString** [comment]
how about Lollypop ?

**Comment by vinceliuice** [comment]
Gnome-terminal screen have a background can not be transparent now, so I don't find away to make gnome-terminal support this

**Comment by vinceliuice** [comment]
Lollypop is ok! I'll make this
