### ISSUE TITLE
Extra side bar 

### ISSUE THREAD

**Issue by Sayan-Ghosh** [vinceliuice/Canta-theme#84]
![Screenshot from 2020-03-08 22-50-00](https://user-images.githubusercontent.com/40402190/76167795-68853780-618f-11ea-9908-b67e39557913.png)
I am getting an extra side bar in the left side whenever I am opening the app desk.

**Comment by vinceliuice** [comment]
This is not a theme issue, this is the default gnome-shell dash bar, dash to dock not disabled this, but dash to panel will disable this, so if you are using dash to panel, this will gone!
