### ISSUE TITLE
[WIP] Gnome 3.36 compatibility

### ISSUE THREAD

**Issue by likeadoc** [vinceliuice/Canta-theme#87]
What needs to be updated:
- notification/calendar tray styling (dark themes look fine -only light & normal themes, notification font color also wrong)
- new extensions app (header bar toggle looks weird, website button color)
- Settings Dialog ( line seperators look weird)
-  Settings Dialog (Power off / Logout dialog styling)
- Shell Dialogs (Layout & spacing needs to be updated)
- Reference https://github.com/nana-4/materia-theme/issues/469
@vinceliuice

**Comment by DaviDev-k** [comment]
I opend a pull request to solve gnome shell popups issues, that could remove duplicate separators and the default theme from calendar and buttons below (I think that are points 1 and 3 of your list @likeadoc)

Did you happen to customize the GDM? I solved the other dialogs problems resetting the app  loginized to default and (re)installing `gnome-shell`

**Comment by vinceliuice** [comment]
I'll fix those

**Comment by vinceliuice** [comment]
Fixed
