### ISSUE TITLE
Problem when displaying checkbox on Firefox on Ubuntu 16.04

### ISSUE THREAD

**Issue by lucaferri** [vinceliuice/Canta-theme#9]
I'm using Firefox on Ubuntu 16.04 (gnome-shell version 3.20.4) and checkboxes are displayed as pink square.

I took a screenshot of the bootstrap website
![immagine](https://user-images.githubusercontent.com/1610830/37295802-5d11c7c8-2619-11e8-9cbb-34478d6e9bf5.png)

I tried to switch back to Adwaita and the problem disappear.
Then I switched again to Canta, emptied browser cache, opened a new tab and the problem appeared again.

**Comment by lucaferri** [comment]
The problem got solved after few restarts.
I think we could close this issue.
Sorry :disappointed:

**Comment by vinceliuice** [comment]
It's OK!
